import { test, expect } from '@playwright/test'

const register = async (page) => {
  await page.getByLabel('Email address').click()
  await page
    .getByLabel('Email address')
    .fill(`bltest+${Math.floor(Math.random() * 1000000000 + 1)}@example.com`)
  await page.getByLabel('Email address').press('Tab')
  await page.getByLabel('Password').fill('rapidvisa')
  await page.getByLabel('I agree to the Boundless Privacy Policy.').check()
  await page
    .getByLabel('Send me important tips and updates about the visa process.')
    .uncheck()
  await page.getByRole('button', { name: 'See Results' }).click()
}

test('0 - LOW Risk - Argentina', async ({ page }) => {
  await page.goto('https://visit-staging.boundless.com/')
  await page.getByRole('button', { name: 'Assess Denial Risk' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Argentina' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await register(page)
  await page.getByRole('heading', { name: 'Low', exact: true }).click()
  await page.getByRole('img', { name: 'ar' }).click()
})

test('1 - LOW - India', async ({ page }) => {
  await page.goto('https://visit-staging.boundless.com/')
  await page.getByRole('button', { name: 'Assess Denial Risk' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'India', exact: true }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await register(page)
  await page.getByRole('heading', { name: 'Low', exact: true }).click()
  await page.getByRole('img', { name: 'in', exact: true }).click()
})

test('2 - SLIGHTLY LOW - Iraq', async ({ page }) => {
  await page.goto('https://visit-staging.boundless.com/')
  await page.getByRole('button', { name: 'Assess Denial Risk' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Iraq' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await register(page)
  await page.getByRole('heading', { name: 'Slightly Low' }).click()
  await page.getByRole('img', { name: 'iq' }).click()
})

test('3 - MODERATE - Mexico', async ({ page }) => {
  await page.goto('https://visit-staging.boundless.com/')
  await page.getByRole('button', { name: 'Assess Denial Risk' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Mexico' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByLabel('No').check()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Bulgaria' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await register(page)
  await page.getByRole('heading', { name: 'Moderate' }).click()
  await page.getByRole('img', { name: 'bg' }).click() // picked BULGARIA above
})

test('4 - SLIGHTLY HIGH - Pakistan', async ({ page }) => {
  await page.goto('https://visit-staging.boundless.com/')
  await page.getByRole('button', { name: 'Assess Denial Risk' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Pakistan' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await register(page)
  await page.getByRole('heading', { name: 'Slightly High' }).click()
})

test('5 - HIGH - Sudan', async ({ page }) => {
  await page.goto('https://visit-staging.boundless.com/')
  await page.getByRole('button', { name: 'Assess Denial Risk' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Sudan', exact: true }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await register(page)
  await page.getByRole('heading', { name: 'High' }).click()
})

test('6 - HIGH - Uzbekistan', async ({ page }) => {
  await page.goto('https://visit-staging.boundless.com/')
  await page.getByRole('button', { name: 'Assess Denial Risk' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Uzbekistan' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Egypt' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await register(page)
  await page.getByRole('heading', { name: 'High' }).click()
})

test('7 - HIGH - El Salvador', async ({ page }) => {
  await page.goto('https://visit-staging.boundless.com/')
  await page.getByRole('button', { name: 'Assess Denial Risk' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'El Salvador' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('combobox', { name: 'Country' }).click()
  await page.getByRole('option', { name: 'Albania' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio No No' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await page.getByRole('button', { name: 'Radio Yes Yes' }).click()
  await page.getByRole('button', { name: 'Next' }).click()
  await register(page)
  await page.getByRole('heading', { name: 'High' }).click()
})